### ISSUE TITLE
[M2] Remove problematic dependencies

### ISSUE THREAD

**Issue by ayoubmansar** [teddyliang/Meta-Mesh-Help-Desk#30]
In #19 , @teddyliang pointed out that there are 2 problematic dependencies from the `requirements.txt` that are not necessarily required for the project. This causes a cryptic `error: legacy-install-failure` on some machines while success on others.

To ensure the project can be successfully deployed across a variety machines, this issue should remove the unnecessary requirements.

**Comment by teddyliang** [comment]
resolved
