### ISSUE TITLE
[M3] [Maintaining Resources] Re-scrape resources

### ISSUE THREAD

**Issue by najclark** [teddyliang/Meta-Mesh-Help-Desk#44]
Since adding the backend database to the web searcher, the web scraping functionality has not been able to work. This issue addresses this.

**Comment by ashwin-godura** [comment]
The BeautifulSoup Api is now properly working and allowing the search engine to web scrape the links. 
<img width="1440" alt="Screenshot 2023-04-18 at 11 46 09 AM" src="https://user-images.githubusercontent.com/73041377/232831541-fe85156d-dc9b-4e13-ad6e-834a4c6fca78.png">
Here "ticket master" is a term that has been scraped from the tech boomers' website so the search engine can recognize the query.
