### ISSUE TITLE
[M3] Search only for resources in the selected category

### ISSUE THREAD

**Issue by najclark** [teddyliang/Meta-Mesh-Help-Desk#46]
# Overview
#47 adds the UI to allow end-users to select a category. This scope of work now updates our search handler to filter for the desired category.

The flow should be as follows:

-> If the user does not select any category from the dropdown, i.e. `value=""`, the search handler should continue to run as before, applying no filters and returning all relevant results.

-> If the user does select a category from the dropdown, the search handler should first retrieve all relevant results, then filter for only resources that contain the filtered category within its category set.

-> If the user maliciously modifies the `?c=...` category parameter when submitting their search request to some category that doesn't exist in the database (e.g. ` http://127.0.0.1:8000/home?c=THIS+CATEGORY+DOES+NOT+EXIST&q=example+query`), safely handle it and act as if no filter was applied.

In addition to implementing the above flows, this scope of work will also need to:
- Ensure that whatever category filter the user selected on the homepage carries over visually to the results page
- Add new tests and update existing ones

# Results
https://user-images.githubusercontent.com/28874539/229739039-fe2608c1-185d-4f3b-b561-6dbc533fd627.mp4

**Comment by ayoubmansar** [comment]
Merged
