### ISSUE TITLE
[M3] Select UI to change search category

### ISSUE THREAD

**Issue by najclark** [teddyliang/Meta-Mesh-Help-Desk#47]
# Overview
This scope of work covers adding a front-facing UI element to allow end-users to filter their search by all available categories.

We'd like this UI element to be simple and non-intrusive. In our preliminary research for this task, we settled on this type of design:
![image](https://user-images.githubusercontent.com/28874539/229736654-39aafc53-6305-4e35-9fa5-21e2f08f25ff.png)

In terms of technical work, the relevant work would include:
- When rendering the search page, also send to the client a list of all category objects so that they can be rendered on the page
- Adding the relevant HTML for the new filter and CSS to beautify it
- Adding Django template language to output each category object to the HTML element's dropdown

# Results
*Default*
![image](https://user-images.githubusercontent.com/28874539/229737274-d783c3f7-7988-4d04-986d-74a877be071a.png)
*Dropdown contents with 2 categories in the database*
![image](https://user-images.githubusercontent.com/28874539/229737448-0072b219-88fa-439f-a47d-c912d3511822.png)

![image](https://user-images.githubusercontent.com/28874539/229737340-c82934ac-6c83-4634-a61c-133b10936785.png)

**Comment by ayoubmansar** [comment]
Merged
