### ISSUE TITLE
[M5]  Limit length of long autocomplete result titles

### ISSUE THREAD

**Issue by sibhy** [teddyliang/Meta-Mesh-Help-Desk#74]
From our user testing, we got feedback that auto-complete felt a bit overwhelming when resource titles were too long. To remedy this, we are implementing a character limit along with adding "..." for resource titles that go over that character limit.

**Comment by teddyliang** [comment]
Instead of using a "..." and truncating the title, a horizontal scroll bar can be added so that the user can still view whole titles without them overwhelming the page
