### ISSUE TITLE
[M3] Investigate Elastic Beanstalk for running Django app

### ISSUE THREAD

**Issue by najclark** [teddyliang/Meta-Mesh-Help-Desk#9]
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html

Following this tutorial on how to deploy a django app using beanstalk.

Looking into: Cost for a given day (based on queries or compute time?)

**Comment by sibhy** [comment]
For the final version of our app, we plan to host it using AWS Elastic Beanstalk. This will make it easier for the MetaMesh team to maintain the app over time, since Elastic Beanstalk abstracts away infrastructure management.
